import Head from "next/head";
import Middle from "~/components/Middle";
import TopCard from "~/components/TopCard";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-screen w-screen bg-gradient-to-tr from-emerald-200 to-indigo-400 flex flex-col items-center">
        <TopCard />
        <Middle />
      </main>
    </>
  );
}
