import Head from "next/head";
import TopCard from "~/components/TopCard";

export default function Home() {
  return (
    <main className="h-screen w-screen bg-gradient-to-tr from-emerald-200 to-indigo-400">
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TopCard />
    </main>
  );
}
